package onlab.AppointmentBookingBackend.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;
import java.util.Calendar;

@DynamoDBTable(tableName = "appointments")
public class Appointment {

    private String id;
    private long dateTime;
    private User company;
    private User user;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return  id;
    }

    public void setId(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "datetime")
    public long getDateTime(){
        return dateTime;
    }

    public void setDateTime(long dt){
        this.dateTime = dt;
    }

    @DynamoDBAttribute(attributeName = "company")
    public User getCompanyId(){
        return company;
    }

    public void setCompanyId(User company){
        this.company = company;
    }

    @DynamoDBAttribute(attributeName = "user")
    public User getUser(){
        return user;
    }

    public void setUser(User user){
        this.user = user;
    }

    @Override
    public String toString() {
        return "Appointment{" +
                "id='" + id + '\'' +
                ", dateTime=" + dateTime +
                ", company=" + company +
                ", user=" + user +
                '}';
    }
}

