package onlab.AppointmentBookingBackend.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;
import java.util.Calendar;

@DynamoDBTable(tableName = "appointments")
@DynamoDBDocument
public class Appointment {

    private String id;
    private long dateTime;
    private User company;
    private User user;
    private String note;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return  id;
    }

    public void setId(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "datetime")
    public long getDateTime(){
        return dateTime;
    }

    public void setDateTime(long dt){
        this.dateTime = dt;
    }

    @DynamoDBAttribute(attributeName = "company")
    public User getCompany(){
        return company;
    }

    public void setCompany(User company){
        this.company = company;
    }

    @DynamoDBAttribute(attributeName = "user")
    public User getUser(){
        return user;
    }

    public void setUser(User user){
        this.user = user;
    }

    @DynamoDBAttribute(attributeName = "note")
    public String getNote() { return note; }

    public void setNote(String note) { this.note = note; }

    @Override
    public String toString() {
        return "Appointment{" +
                "id='" + id + '\'' +
                ", dateTime=" + dateTime +
                ", company=" + company +
                ", user=" + user +
                ", note='" + note + '\'' +
                '}';
    }
}

