package onlab.AppointmentBookingBackend.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;
import java.util.Calendar;

@DynamoDBTable(tableName = "appointments")
public class Appointment {

    private String id;
    private long dateTime;
    private String companyId;
    private String userId;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return  id;
    }

    public void setId(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "datetime")
    public long getDateTime(){
        return dateTime;
    }

    public void setDateTime(long dt){
        this.dateTime = dt;
    }

    @DynamoDBAttribute(attributeName = "companyId")
    public String getCompanyId(){
        return companyId;
    }

    public void setCompanyId(String id){
        this.companyId = id;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public String getUserId(){
        return userId;
    }

    public void setUserId(String id){
        this.userId = id;
    }

    @Override
    public String toString() {
        return "Appointment{" +
                "id='" + id + '\'' +
                ", dateTime=" + dateTime +
                ", companyId='" + companyId + '\'' +
                ", userId='" + userId + '\'' +
                '}';
    }
}

