package onlab.AppointmentBookingBackend.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "users")
@DynamoDBDocument
public class User {
    private String id;
    private String firstName;
    private String lastName;
    private String companyName;
    private String email;
    private String password;
    private String role;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return id;
    }

    public void setId(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "firstname")
    public String getFirstName(){
        return  firstName;
    }

    public void setFirstName(String firstName){
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastname")
    public String getLastName(){
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "email")
    public String getEmail(){
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "password")
    public String getPassword(){
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @DynamoDBAttribute(attributeName = "role")
    public String getRole(){
        return role;
    }

    public void setRole(String role){
        this.role = role;
    }


    @DynamoDBAttribute(attributeName = "companyName")
    public String getCompanyName(){
        return  companyName;
    }

    public void setCompanyName(String companyName){
        this.companyName = companyName;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", companyName='" + companyName + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}
